#!/bin/bash

STATEDIR="/var/lib/swl"
ORIG_PID_MAX_FILE="$STATEDIR/orig_kernel.pid_max"

mkdir -p "$STATEDIR"

if [ -f "$ORIG_PID_MAX_FILE" ]; then
    ORIG_PID_MAX=$(cat "$ORIG_PID_MAX_FILE")
    echo "[$(date)] Resetting kernel.pid_max to $ORIG_PID_MAX..."
    sysctl -w kernel.pid_max="$ORIG_PID_MAX"
else
    echo "[$(date)] No original kernel.pid_max value found to reset."
fi