#!/bin/bash

# Check if waydroid exists
if [ ! -f /usr/bin/waydroid ]; then
    echo "[$(date)] ERROR: Waydroid does not exist!"
    kdialog --sorry "Cannot stop Waydroid. Waydroid does not exist!"
    exit 1
fi

# Stop the waydroid-container service
echo "[$(date)] Stopping waydroid-container.service..."
/usr/bin/systemctl stop waydroid-container.service

systemctl status waydroid-container.service | grep -i running
if [ $? -eq 0 ]; then
    echo "[$(date)] ERROR: Waydroid container is still running."
    kdialog --sorry "Something went wrong. Waydroid container is still running."
    exit