#!/bin/bash

# restore the kernel.pid_max to the default value and then delete the temp file created
sysctl -w kernel.pid_max=$(cat /home/deck/Android_Waydroid/orig_kernel.pid_max)
rm -f /home/deck/Android_Waydroid/orig_kernel.pid_max

# reset cage
cage -- bash -c 'wlr-randr'

# stop the waydroid container
sudo /usr/bin/systemctl stop waydroid-container.service
